### PR TITLE
feat: add civic evidence filters

### PR DESCRIPTION
**Pull request by HomoPolyethylen**
## PR checklist

- [x] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/variantmtb/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/variantmtb _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [x] Make sure your code lints (`nf-core lint`).
- [x] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [x] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [x] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

* added civic evidence filter support from querynator to variantmtb
* added a `actionability` profile with common filters for convenience
* updated modules

### CODE REVIEW

**Comment by HomoPolyethylen** [comment]
linting test fails because github action uses nf-core tools v3.0.1
using v2.14.1 locally works. What shall we do? change the action to force it to use v2.14.1? or ignore the linting test fails?

**Comment by mapo9** [comment]
you cant update locally and check?
otherwise it's fine to ignore

**Review by mapo9 — APPROVED** [review]
👍

**Comment by HomoPolyethylen** [comment]
Updating nf-tools would mean I would need to perform a template update for 3.0.1 (if I want the tests to pass)

**Pull request merged**
